// src/App.svelte
<script lang="ts">
  import TailwindCss from './TailwindCSS.svelte';
  import Header from './lib/Header.svelte';
  import Banner from './lib/Banner.svelte';
  import About from './lib/About.svelte';
  import Prestations from './lib/Prestations.svelte';
  import Testimonials from './lib/Testimonials.svelte';
  import Footer from './lib/Footer.svelte';
  import ScrollTopButton from './lib/ScrollTopButton.svelte';
</script>

<TailwindCss />
<Header/>
<Banner />
<About />
<Prestations />
<Testimonials />
<Footer />
<ScrollTopButton />

// src/App.jsx
import './App.css'
import Header from './components/Header';
import Banner from './components/Banner';
import Footer from './components/Footer';
import Prestations from './components/Prestations';
import Testimonials from './components/Testimonials';
import About from './components/About';
import ScrollTopButton from './components/ScrollTopButton';

function App() {
  return (
    <>
      <Header id="top"/>
      <Banner />
      <About />
      <Prestations />
      <Testimonials />
      <Footer />
      <ScrollTopButton />
    </>
    
  )
}

export default App
